name: Python package

on: [push]

jobs:
  nox:
    name: Coverage, Docs, Lint, and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
      run: |
        pip install .[ci]
    - name: Lint
      run: |
        nox -s lint
        nox -s lint -- prod
        nox -s lint_modules tests cover
    - name: Tests
      run: |
        nox -s test  
